#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SIFCONT.Resource", IsApplication=true)]

namespace SIFCONT
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int LEMANU128x128 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int LEMANU16x16 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int LEMANU24x24 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int LEMANU256x256 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int LEMANU32x32 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int LEMANU48x48 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int LEMANU64x64 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int LEMANU96x96 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int unlock = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int cmdIniciar = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int lblBienvenida = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int lblClave = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int lblMensaje = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int lblUsuario = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int picLogo = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int txtClave = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int txtUsuario = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Form_Principal = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Sincronizar_Actividad = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
